# What is PyTorch?

In [1]:
import torch

## The torch.Tensor object

In [12]:
# uninitialized matrix
x = torch.empty(5, 3)
print(x)
print(type(x))

tensor([[-3.3444e-07,  4.5838e-41, -3.3444e-07],
        [ 4.5838e-41,  1.8522e+28,  1.8057e+28],
        [ 3.0999e-15,  2.2210e+23,  7.2076e+31],
        [ 2.0196e-19,  1.8888e+31,  1.2570e+19],
        [ 1.8522e+28,  1.8057e+28,  1.8920e-19]])
<class 'torch.Tensor'>


In [4]:
# randomly initialized matrix
x = torch.randn(5, 3)
print(x)

tensor([[ 0.9660, -1.7220, -0.2695],
        [ 0.3350,  1.5992,  1.7784],
        [ 0.8081,  0.0377,  1.6873],
        [ 0.2794, -0.7024, -1.2612],
        [-1.3732, -0.9858, -0.6577]])


In [5]:
# zeros with dtype long (64-bit int?)
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
# constructed directly from data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [13]:
# create a tensor based on an existing tensor
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.5251,  2.6987, -0.8333],
        [-0.4452, -1.9423, -1.1414],
        [ 0.0739,  0.6392, -0.3557],
        [ 0.4490, -1.2581,  0.5022],
        [-0.0640,  0.1102, -0.1358]])


In [43]:
# size/dimensions
print(x.size())
print(x.shape)

torch.Size([4, 4])
torch.Size([4, 4])


## Operations

In [22]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 2.3329,  2.9037, -0.3463],
        [ 0.2770, -1.5562, -0.9785],
        [ 0.7536,  1.3836,  0.5315],
        [ 0.8056, -0.4074,  0.9709],
        [ 0.6510,  1.0167,  0.5308]])


In [23]:
print(torch.add(x, y))

tensor([[ 2.3329,  2.9037, -0.3463],
        [ 0.2770, -1.5562, -0.9785],
        [ 0.7536,  1.3836,  0.5315],
        [ 0.8056, -0.4074,  0.9709],
        [ 0.6510,  1.0167,  0.5308]])


In [24]:
# provide an output tensor as an argument
# kinda like numpy's out arguments
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 2.3329,  2.9037, -0.3463],
        [ 0.2770, -1.5562, -0.9785],
        [ 0.7536,  1.3836,  0.5315],
        [ 0.8056, -0.4074,  0.9709],
        [ 0.6510,  1.0167,  0.5308]])


In [25]:
# Another way of adding
y.add(x)

tensor([[ 2.3329,  2.9037, -0.3463],
        [ 0.2770, -1.5562, -0.9785],
        [ 0.7536,  1.3836,  0.5315],
        [ 0.8056, -0.4074,  0.9709],
        [ 0.6510,  1.0167,  0.5308]])

In [27]:
# post-fixing an operation with `_` mutates a tensor in-place
y.add_(x)
print(y)

tensor([[ 2.3329,  2.9037, -0.3463],
        [ 0.2770, -1.5562, -0.9785],
        [ 0.7536,  1.3836,  0.5315],
        [ 0.8056, -0.4074,  0.9709],
        [ 0.6510,  1.0167,  0.5308]])


In [34]:
# can use numpy-like slicing
print(y[:, 1])
print(y[0,:-1])

tensor([ 2.9037, -1.5562,  1.3836, -0.4074,  1.0167])
tensor([2.3329, 2.9037])


In [41]:
# resize tensor
# apparently using .resize() works, but is deprecated
x = torch.randn(4, 4)
print(x.view(16))
print(x.view(-1, 8))
print(x.view(-1, 8).size())

tensor([ 1.5480,  0.8996,  0.4670,  0.0698,  1.1280, -0.6655,  0.1457,  2.4475,
        -0.6291, -0.9696,  1.2041,  2.9257,  0.1392, -0.7373,  0.4538, -0.1087])
tensor([[ 1.5480,  0.8996,  0.4670,  0.0698,  1.1280, -0.6655,  0.1457,  2.4475],
        [-0.6291, -0.9696,  1.2041,  2.9257,  0.1392, -0.7373,  0.4538, -0.1087]])
torch.Size([2, 8])


In [44]:
# Using .item() on a scalar returns a python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.5825])
-1.58245050907135


## Converting back and forth between NumPy

In [46]:
a = torch.ones(5)
print(a)

# convert to numpy
b = a.numpy()
print(b)

# and back to Tensor
import numpy as np
c = torch.from_numpy(b)
d = torch.tensor(b)
print(c)
print(d)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])


In [47]:
# The tensor created with torch.from_numpy()is linked to the numpy array,
# so be careful of mutations. The one created from torch.tensor isn't though
np.add(b, 1, out=b)
print(b)
print(c)
print(d)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.])
tensor([1., 1., 1., 1., 1.])


## CUDA Tensors

In [49]:
# check if CUDA is available
print("CUDA available: ", torch.cuda.is_available())

if torch.cuda.is_available():
    device = torch.device("cuda") # CUDA device object
    y = torch.ones_like(x, device=device) # directly create tensor on GPU
    x = x.to(device) # convert device using .to()
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

CUDA available:  True
tensor([-0.5825], device='cuda:0')
tensor([-0.5825], dtype=torch.float64)
